services:
  expenseapi:
    image: expenseapi:latest
    build:
      context: .
      dockerfile: ExpenseTracker/Dockerfile
    ports:
      - 5109:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=server=db;port=3307;database=expensetracker;user=root;password=3277;
    depends_on:
      - db
    entrypoint: >
      sh -c "
        echo '⏳ Waiting for MySQL...';
        until nc -z db 3307;
        do
          sleep 3;
        done;
        echo '✅ MySQL is ready, starting API';
        dotnet ExpenseTracker.dll
      "

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=3277
      - MYSQL_DATABASE=expensetracker
      - MYSQL_TCP_PORT=3307
    ports:
      - "3307:3307"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: